<Project>
  <!-- IMPORTANT: Manually import the root versions -->
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Packages.props', '$(MSBuildThisFileDirectory)../'))" />
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="10.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
    <PackageVersion Include="TngTech.ArchUnitNET.xUnit" Version="0.13.3" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.6" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.14.0" />
    <PackageVersion Include="Testcontainers.RabbitMq" Version="4.14.0" />
    <PackageVersion Include="Testcontainers.Redis" Version="4.14.0" />
    <PackageVersion Include="Respawn" Version="7.0.0" />
  </ItemGroup>
</Project>