@Users.Api_HostAddress = http://localhost:5161
@UserId = 1

POST {{Users.Api_HostAddress}}/api/users/registration
Accept: application/json
X-Identity-UserId: {{UserId}}
###


POST {{Users.Api_HostAddress}}/api/users/login
Accept: application/json
X-Identity-UserId: {{UserId}}
###

POST {{Users.Api_HostAddress}}/api/users/refreshToken
Accept: application/json
X-Identity-UserId: {{UserId}}

###