<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="TngTech.ArchUnitNET.xUnit" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Bookings.Api\Bookings.Api.csproj" />
      <ProjectReference Include="..\..\Bookings.Application\Bookings.Application.csproj" />
      <ProjectReference Include="..\..\Bookings.Domain\Bookings.Domain.csproj" />
      <ProjectReference Include="..\..\Bookings.Sql\Bookings.Sql.csproj" />
      <ProjectReference Include="..\..\Events.Api\Events.Api.csproj" />
      <ProjectReference Include="..\..\Events.Application\Events.Application.csproj" />
      <ProjectReference Include="..\..\Events.Domain\Events.Domain.csproj" />
      <ProjectReference Include="..\..\Events.Mongo\Events.Mongo.csproj" />
      <ProjectReference Include="..\..\Users.Api\Users.Api.csproj" />
    </ItemGroup>

</Project>