using System.Web;
using Braintree;
using PaymentAdapters.Fixtures;
using PaymentProvider.Abstractions;
using PaymentProvider.Exceptions;
using PaymentProvider.Models;

namespace PaymentAdapters.BraintreeProvider;

// Notifications are generated by the Braintree SDK's own WebhookTesting with the configured keys, so
// the signature scheme under test is Braintree's, not one this suite made up.
public sealed class BraintreeWebhookTests
{
    private readonly IPaymentGateway _gateway = Gateways.Braintree(new FakeHttpServer());

    private readonly BraintreeGateway _signer = new(
        Braintree.Environment.SANDBOX, Gateways.BraintreeMerchantId, Gateways.BraintreePublicKey, Gateways.BraintreePrivateKey);

    [Fact]
    public void A_signed_settlement_is_a_success_for_that_transaction()
    {
        var webhook = Parse(Sample(WebhookKind.TRANSACTION_SETTLED, "tx_7"));

        Assert.NotNull(webhook);
        Assert.Equal("tx_7", webhook.Payment.ProviderReference);
        Assert.Equal(PaymentStatus.Succeeded, webhook.Payment.Status);
    }

    [Fact]
    public void A_signed_settlement_decline_is_a_failure()
    {
        var webhook = Parse(Sample(WebhookKind.TRANSACTION_SETTLEMENT_DECLINED, "tx_7"));

        Assert.Equal(PaymentStatus.Failed, webhook!.Payment.Status);
    }

    [Fact]
    public void Parsing_the_same_delivery_twice_gives_the_same_event_id_to_dedupe_on()
    {
        var body = Sample(WebhookKind.TRANSACTION_SETTLED, "tx_7");

        Assert.Equal(Parse(body)!.EventId, Parse(body)!.EventId);
    }

    [Fact]
    public void A_settlement_and_a_settlement_decline_for_one_transaction_are_different_events()
    {
        var settled = Parse(Sample(WebhookKind.TRANSACTION_SETTLED, "tx_7"))!;
        var declined = Parse(Sample(WebhookKind.TRANSACTION_SETTLEMENT_DECLINED, "tx_7"))!;

        Assert.NotEqual(settled.EventId, declined.EventId);
    }

    [Theory]
    [InlineData(WebhookKind.CHECK)]
    [InlineData(WebhookKind.DISPUTE_OPENED)]
    [InlineData(WebhookKind.DISBURSEMENT)]
    [InlineData(WebhookKind.SUBSCRIPTION_CANCELED)]
    public void A_notification_that_is_not_about_a_transaction_is_verified_then_ignored(WebhookKind kind)
    {
        Assert.Null(Parse(Sample(kind, "id_1")));
    }

    [Fact]
    public void A_payload_changed_after_signing_is_refused()
    {
        var genuine = _signer.WebhookTesting.SampleNotification(WebhookKind.TRANSACTION_SETTLEMENT_DECLINED, "tx_7");
        var forged = _signer.WebhookTesting.SampleNotification(WebhookKind.TRANSACTION_SETTLED, "tx_7");

        AssertRefused(Form(genuine["bt_signature"], forged["bt_payload"]));
    }

    [Fact]
    public void A_notification_signed_with_another_merchant_s_keys_is_refused()
    {
        var attacker = new BraintreeGateway(Braintree.Environment.SANDBOX, "other_merchant", Gateways.BraintreePublicKey, "other_private_key");
        var sample = attacker.WebhookTesting.SampleNotification(WebhookKind.TRANSACTION_SETTLED, "tx_7");

        AssertRefused(Form(sample["bt_signature"], sample["bt_payload"]));
    }

    [Theory]
    [InlineData("")]
    [InlineData("bt_payload=abc")]
    [InlineData("bt_signature=abc")]
    [InlineData("bt_signature=&bt_payload=")]
    [InlineData("""{"bt_signature":"a","bt_payload":"b"}""")]
    public void A_body_without_both_signed_fields_is_refused(string body)
    {
        AssertRefused(body);
    }

    [Fact]
    public void A_signature_that_is_garbage_is_refused_not_a_crash()
    {
        var sample = _signer.WebhookTesting.SampleNotification(WebhookKind.TRANSACTION_SETTLED, "tx_7");

        AssertRefused(Form("no-pipe-here", sample["bt_payload"]));
    }

    [Fact]
    public void A_payload_that_is_not_base64_is_refused_not_a_crash()
    {
        AssertRefused(Form(Gateways.BraintreePublicKey + "|deadbeef", "%%%not-base64%%%"));
    }

    private WebhookEvent? Parse(string body) => _gateway.ParseWebhook(new WebhookRequest(body, new Dictionary<string, string>()));

    private string Sample(WebhookKind kind, string id)
    {
        var sample = _signer.WebhookTesting.SampleNotification(kind, id);
        return Form(sample["bt_signature"], sample["bt_payload"]);
    }

    private static string Form(string signature, string payload) =>
        $"bt_signature={HttpUtility.UrlEncode(signature)}&bt_payload={HttpUtility.UrlEncode(payload)}";

    private void AssertRefused(string body)
    {
        var exception = Assert.Throws<PaymentProviderException>(() => Parse(body));
        Assert.Equal(PaymentProviderErrorKind.InvalidSignature, exception.Kind);
    }
}
